## Build PowerDNS config
- name: "Build PowerDNS config variables"
  set_fact:
    _pdns_bind_dnssec_db: "{{ pdns_secondary_zones_dir }}/dnssec.db"
    _pdns_local_address: "{{ (dummy_interfaces.anycast_auth_dns.ip4 + dummy_interfaces.anycast_auth_dns.ip6) }}"

- name: "Build PowerDNS BIND backend config"
  set_fact:
    _pdns_backends:
      bind: &bind_backend_config
        config: "/etc/powerdns/named.conf"
        dnssec-db: "{{ _pdns_bind_dnssec_db }}"

- name: "Create PowerDNS config folder"
  file:
    path: "/etc/powerdns"
    state: directory

# XXX: this duplicates work, but the pdns role will fail to start the server if we don't create the bind DNSSEC DB
# beforehand... https://github.com/PowerDNS/pdns-ansible/issues/3
- name: Create pdns system group
  group:
    name: pdns
    system: true
- name: Create pdns system account
  user:
    name: pdns
    group: pdns
    system: true
    password_lock: true
- name: Install pdns-server (for pdnsutil)
  apt:
    name: pdns-server
    state: present

## Create a writeable data dir for receiving secondary zones from *.master.delegation-servers.dn42
- name: "Create PowerDNS secondary zones folder"
  file:
    path: "{{ pdns_secondary_zones_dir }}/"
    state: directory
    owner: pdns
    group: pdns
    mode: '0755'

- name: "Create DNSSEC DB for PowerDNS secondary zones"
  command:
    cmd: pdnsutil create-bind-db {{ _pdns_bind_dnssec_db }}
    creates: "{{ _pdns_bind_dnssec_db }}"
  become_user: pdns
  notify:
    - Reconfigure PowerDNS

- name: "Template named.conf for PowerDNS"
  template:
    src: "named.conf.j2"
    dest: "/etc/powerdns/named.conf"
    mode: '0644'
  notify:
    - Reconfigure PowerDNS

- import_role:
    name: PowerDNS.pdns
  vars:
    pdns_install_repo: "" # use system default
    pdns_config:
      local-address: "{{ _pdns_local_address | join(', ') }}"
      secondary: "{{ dns_dn42_secondary_zones is defined | bool }}"
      allow-notify-from: "{{ dns_dn42_primary_servers | join(', ') }}"
      allow-axfr-ips: "172.20.0.0/14, 10.0.0.0/8, 172.31.0.0/16, fd00::/8"
    pdns_backends: "{{ _pdns_backends }}"
    pdns_service_overrides:
      # Work around errors described at https://github.com/PowerDNS/pdns_recursor-ansible/issues/69
      User: "{{ pdns_user }}"
      Group: "{{ pdns_group }}"
      # Start/stop
      ExecStartPre: "+ifup {{ dummy_interfaces.anycast_auth_dns.ifname }} --force"
      ExecStopPost: "+ip link del {{ dummy_interfaces.anycast_auth_dns.ifname }}"
      # For secondary zone DBs
      ReadWritePaths: "{{ pdns_secondary_zones_dir }}"
    pdns_disable_handlers: "{{ 'pdns' }}"

- name: "Synchronize DNS zones"
  synchronize:
    src: "{{ playbook_dir }}/global-config/dns-zones/"
    dest: "{{ dns_zones_dir }}"
    checksum: true
    archive: false
    delete: true
    recursive: true
  notify:
    - Reconfigure PowerDNS
